# Generated by Django 5.2.8 on 2026-01-10 01:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload MP3', null=True, upload_to='sermons/audio/', validators=[core.validators.validate_file_size, core.validators.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/', validators=[core.validators.validate_image_size]),
        ),
    ]
