# Generated by Django 5.2.8 on 2025-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark as completed to hide from public view.'),
        ),
    ]
