# Generated by Django 5.2.8 on 2026-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='is_private',
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='request_followup',
            field=models.BooleanField(default=False, help_text='Request a pastor to follow up (Login required)'),
        ),
    ]
