# Generated by Django 5.2.8 on 2026-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_remove_prayerrequest_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='followed_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_followed_up',
            field=models.BooleanField(default=False, help_text='Has staff followed up with this request?'),
        ),
    ]
