# Generated by Django 5.2.8 on 2025-12-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order for manual sorting on homepage')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Problem-based title, e.g. 'Why God Feels Silent'", max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('problem_text', models.TextField(help_text='Short, relatable paragraphs. Reader must feel understood.')),
                ('scripture_citation', models.CharField(help_text="e.g. 'Psalm 23:1-4'", max_length=100)),
                ('scripture_text', models.TextField(help_text='The actual Bible text')),
                ('explanation_text', models.TextField(help_text='Plain English. No church jargon. Context + meaning.')),
                ('truth_text', models.TextField(help_text='Clear, sometimes uncomfortable. Scripture-aligned. Hopeful but honest.')),
                ('action_text', models.TextField(help_text='One practical action.')),
                ('reflection_question', models.TextField(help_text='One reflection question.')),
                ('audio_url', models.URLField(blank=True, help_text='Optional link to audio version')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='core.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
