# Generated by Django 5.2.8 on 2025-12-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional link to YouTube video'),
        ),
    ]
