# Generated by Django 5.2.8 on 2025-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_stream_url', models.URLField(blank=True, help_text='Embed URL for live stream')),
                ('is_live_now', models.BooleanField(default=False)),
                ('giving_enabled', models.BooleanField(default=True)),
                ('flutterwave_public_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
