# Generated by Django 5.2.8 on 2026-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='Igniting a Burning Generation On Fire For Jesus', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtext',
            field=models.TextField(default='We are a global movement raising a passionate generation empowered to influence nations with the fire and truth of Jesus.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_text',
            field=models.TextField(default='Raising, Building and Equipping People as Kingdom Ambassadors in Every Sphere of Human Influence.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_text',
            field=models.TextField(default='Raising a Burning Generation. Empowering young believers to live passionately for Jesus.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='YouTube or generic stream link'),
        ),
    ]
