# Generated by Django 5.2.8 on 2026-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='live_page_background',
            field=models.ImageField(blank=True, help_text='Background image for the Watch Live page', null=True, upload_to='core/backgrounds/'),
        ),
    ]
